[keyboard]
name = "roBa-rmk"
product_name = "roBa-rmk"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
# board = "XIAO BLE"
board = "nice!nano_v2"

[rmk]
ble_profiles_num = 5

# controller_channel_pubs = 13 # default: 12
# controller_channel_subs = 9 # default: 8

[event.layer_change]
subs = 2

[event.pointing]
subs = 3

[event.action]
subs = 1

[ble]
enabled = true

default_tx_power = 8
use_2m_phy = true


#[split]

#[layout]
#rows = 4
#cols = 5
#row_offset = 0
#col_offset = 6

#[split.central]
#[battery]
# XIAO BLE nRF52840: Battery voltage is read from P0.31 (AIN7) with a voltage divider (1MΩ + 510kΩ), measuring across 510kΩ.
# Note that P0.14 (VBAT_ENABLE) must be set LOW to enable battery voltage reading. This is done via [[split.central.output]] and [[split.peripheral.output]] configs.
#battery_adc_pin = "P0_31"
#adc_divider_measured = 510
#adc_divider_total = 1510

#[[split.central.output]]
#[[output]]
# Set P0.14 (VBAT_ENABLE) to LOW to enable battery voltage reading for XIAO BLE.
#pin = "P0_14"
#initial_state_active = true
#low_active = true

[matrix]
#rows = 4
#cols = 5
matrix_type = "normal"
row_pins = ["P0_03", "P0_28", "P0_29", "P1_11"]
col_pins = ["P1_15", "P1_14", "P1_13", "P1_12", "P0_10"]

# XIAO BLE nRF52840: Battery voltage is read from P0.31 (AIN7) with a voltage divider (1MΩ + 510kΩ), measuring across 510kΩ.
# Note that P0.14 (VBAT_ENABLE) must be set LOW to enable battery voltage reading. This is done via [[split.central.output]] and [[split.peripheral.output]] configs.
# battery_adc_pin = "P0_31"
# adc_divider_measured = 510
# adc_divider_total = 1510


[input_device]
[[input_device.pmw3610]]
name = "trackball0"
spi.instance = "bitbang0"
spi.sck = "P0_05"
spi.mosi = "P0_04"
spi.miso = "P0_04"
spi.cs = "P0_09"
motion = "P0_02"

report_hz = 75

force_awake = false
smart_mode = true

cpi = 800
invert_x = true
# invert_y = true
# swap_xy = true

[storage]
# Uncomment to clear keymap data modified via Vial
# clear_layout = true

# Uncomment to clear ALL storage (keymap and BLE bonds)
# clear_storage = true

[layout]
rows = 4
cols = 5
map = """
(0,0) (0,1) (0,2) (0,3) (0,4)
(1,0) (1,1) (1,2) (1,3) (1,4)
(2,0) (2,1) (2,2) (2,3) (2,4)
(3,0) (3,1) (3,2) (3,3) (3,4)
"""

[behavior]
morse = { hold_timeout = "200ms", permissive_hold = true, quick_tap_timeout = "250ms" }

[[behavior.auto_mouse_layer]]
target_layer = 5
timeout = "10000ms"
threshold = 1
deactivate_on_key = true
extra_mouse_keys = ["LCtrl", "LShift", "LAlt", "LGui"]
reset_timeout_on_key = true

[aliases]
# User0 - User(N-1): switch to specific profile, where N is ble_profiles_num
bt_sel_0 = "User0"
bt_sel_1 = "User1"
bt_sel_2 = "User2"
bt_sel_3 = "User3"
bt_sel_4 = "User4"

# UserN: switch to next profile
bt_next = "User5"

# User(N+1): switch to previous profile
bt_prev = "User6"

# User(N+2): clear current profile bond info
bt_clr = "User7"

# User(N+3): switch default output between USB/BLE
bt_switch = "User8"


[keymap]
layers = 8

[[keymap.layer]]
name = "Layer 0 - Default"
keys = """
LT(7,Y)        U   I      O     P
H              J   K      L     LT(6,Minus)
N              M   Comma  Dot   Slash
LT(1,Enter)    _   _      _     Escape
"""
#encoders = [["PageDown", "PageUp"]]

[[keymap.layer]]
name = "Layer 1"
keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]

[[keymap.layer]]
name = "Layer 2"
keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]

[[keymap.layer]]
name = "Layer 3"
keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]

[[keymap.layer]]
name = "Layer 4"
keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]

[[keymap.layer]]
name = "Layer 5"
keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]

[[keymap.layer]]
name = "Layer 6"
keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]

[[keymap.layer]]
name = "Layer 7 - Configuration"

keys = """
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
_    _    _    _    _
"""
#encoders = [["_", "_"]]
