[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.build-central]
command = "cargo"
args = ["build", "--release", "--bin", "central"]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.build]
dependencies = ["build-central"]

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "roBa-central.hex",
]
dependencies = ["build-central"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "roBa-central.hex",
    "--output-path",
    "roBa-central.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-central"]

[tasks.uf2]
dependencies = ["uf2-central"]

[tasks.flash-uf2.linux]
script_runner = "bash"
script = '''
if grep -q -i "Microsoft" /proc/version; then
    powershell.exe -ExecutionPolicy Bypass -File scripts/flash.ps1 -Uf2File "$(wslpath -w ${@})"
else
    echo "Flashing is not supported on this platform." >&2
    exit 1
fi
'''

[tasks.flash-uf2.windows]
command = "powershell.exe"
args = [
    "-ExecutionPolicy", "Bypass",
    "-File", "scripts/flash.ps1",
    "-Uf2File", "${@}"
]

[tasks.flash-uf2.mac]
command = "bash"
args = ["scripts/flash.sh", "${@}"]

[tasks.flash-central]
command = "cargo"
args = ["make", "flash-uf2", "roBa-central.uf2"]
dependencies = ["uf2-central"]

[tasks.flash-peripheral]
command = "cargo"
args = ["make", "flash-uf2", "roBa-peripheral.uf2"]
dependencies = ["uf2-peripheral"]

[tasks.flash]
dependencies = ["flash-central"]
