name: Build RMK firmware
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
#   push:
#     paths:
#       - "**"

jobs:
  # build:
  #   uses: haobogu/rmk/.github/workflows/user_build.yml@main
  #   with:
  #     keyboard_toml_path: "keyboard.toml"
  #     vial_json_path: "vial.json"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install clang dependencies
        run: sudo apt-get update && sudo apt-get install -y libclang-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf

      - name: Rust Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install cargo-make
        uses: taiki-e/install-action@18b1216eba7f8039b0f8d131d5473787f0edce68 # v2.85.3
        with:
          tool: cargo-make

      - name: Build UF2
        run: cargo make uf2

      - name: Calculate hash
        run: |
          sha256sum *.uf2

      - name: Upload artifact (central)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: roBa-central.uf2

      - name: Upload artifact (peripheral)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: hashFiles('roBa-peripheral.uf2') != ''
        with:
          archive: false
          path: roBa-peripheral.uf2


